<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Testingsuite" duration-ms="69101" started-at="2020-08-10T15:30:54Z" finished-at="2020-08-10T15:32:03Z">
    <groups>
    </groups>
    <test name="Covid test" duration-ms="69101" started-at="2020-08-10T15:30:54Z" finished-at="2020-08-10T15:32:03Z">
      <class name="selenium2.ExcelTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:selenium2.ExcelTest@357246de]" name="beforeTest" is-config="true" duration-ms="1342" started-at="2020-08-10T21:00:54Z" finished-at="2020-08-10T21:00:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="a_Test()[pri:0, instance:selenium2.ExcelTest@357246de]" name="a_Test" duration-ms="10073" started-at="2020-08-10T21:00:55Z" finished-at="2020-08-10T21:01:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [CoViD-19 Test Report] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [CoViD-19 Test Report] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at selenium2.ExcelTest.a_Test(ExcelTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- a_Test -->
        <test-method status="PASS" signature="b_Test()[pri:1, instance:selenium2.ExcelTest@357246de]" name="b_Test" duration-ms="57678" started-at="2020-08-10T21:01:05Z" finished-at="2020-08-10T21:02:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- b_Test -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:selenium2.ExcelTest@357246de]" name="afterTest" is-config="true" duration-ms="0" started-at="2020-08-10T21:02:03Z" finished-at="2020-08-10T21:02:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- selenium2.ExcelTest -->
    </test> <!-- Covid test -->
  </suite> <!-- Testingsuite -->
</testng-results>
